services:
  fastapi:
    image: fastapi
    container_name: fastapi
    env_file:
      - .env
    ports:
      - 8000:8000
    command: /bin/bash -c "sleep 5 && python -m alembic upgrade head && python -m uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    depends_on:
      - database
  database:
    image: postgres
    env_file:
      - .env